// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentModels
{
    public partial class ContentPage
    {
        public const string Codename = "content_page";
        public const string DescriptionCodename = "description";
        public const string GatsbyTemplateCodename = "gatsby_template";
        public const string MetaDescriptionCodename = "meta_description";
        public const string TitleCodename = "title";

        public string Description { get; set; }
        public IEnumerable<IMultipleChoiceOption> GatsbyTemplate { get; set; }
        public string MetaDescription { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
    }
}